# Generated by Django 5.0 on 2025-07-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sweet_images/'),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='category',
            field=models.CharField(choices=[('MILK', 'Milk Based'), ('DRY', 'Dry Fruit'), ('SUGAR', 'Sugar Based'), ('BENGALI', 'Bengali Sweets'), ('CHOCOLATE', 'Chocolate Sweets')], max_length=50),
        ),
    ]
