# Generated by Django 5.0 on 2025-07-26 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0002_sweet_image_alter_sweet_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedSweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('sweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet_app.sweet')),
            ],
        ),
    ]
