# Generated by Django 5.0 on 2025-07-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0003_purchasedsweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedsweet',
            name='buyer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchasedsweet',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='sweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sweet_app.sweet'),
        ),
    ]
