# Generated by Django 5.0 on 2025-07-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0004_purchasedsweet_buyer_email_purchasedsweet_buyer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedsweet',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='purchasedsweet',
            name='buyer_name',
        ),
        migrations.AddField(
            model_name='purchasedsweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
