# Generated by Django 5.0 on 2025-07-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0005_remove_purchasedsweet_buyer_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedSweet',
        ),
    ]
