# Generated by Django 5.0 on 2025-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0007_purchasedsweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedsweet',
            name='user',
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
