# Generated by Django 5.0 on 2025-07-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0009_purchasedsweet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedsweet',
            name='user',
        ),
    ]
