# Generated by Django 5.0 on 2025-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0010_remove_purchasedsweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedsweet',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
