# Generated by Django 5.0 on 2025-07-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0011_purchasedsweet_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
