# Generated by Django 5.0 on 2025-07-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0012_alter_purchasedsweet_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
