# Generated by Django 5.0 on 2025-07-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0013_alter_purchasedsweet_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
