# Generated by Django 5.0 on 2025-07-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0014_alter_purchasedsweet_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='unit_type',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('WEIGHT', 'Weight (kg)')], default='PIECE', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of pieces or grams'),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit or per kg', max_digits=6),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='quantity',
            field=models.PositiveIntegerField(help_text='In units or grams (for weight)'),
        ),
    ]
