# Generated by Django 5.0 on 2025-07-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0015_sweet_unit_type_alter_purchasedsweet_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='unit_type',
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
