# Generated by Django 5.0 on 2025-07-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0016_remove_sweet_unit_type_alter_purchasedsweet_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedsweet',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchasedsweet',
            name='weight_in_grams',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedsweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
