# Generated by Django 5.0 on 2025-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0018_rename_weight_in_grams_purchasedsweet_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='unit_type',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('PCS', 'Pieces')], default='PCS', max_length=3),
        ),
    ]
