# Generated by Django 5.0 on 2025-07-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0019_sweet_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='unit_type',
        ),
    ]
