# Generated by Django 5.0 on 2025-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_app', '0020_remove_sweet_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='unit_type',
            field=models.CharField(default='PCS', max_length=3),
        ),
    ]
